- name: catalogue
  hosts: catalogue
  become: yes

  tasks:
  - name: Enable Node.js 18 repository
    ansible.builtin.command: dnf install -y nodejs-18*
  
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs18
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory