- name: catalogue
  hosts: catalogue
  become: yes

  tasks:
    - name: Enable Node.js 18 module
      ansible.builtin.command: dnf module enable nodejs:18 -y

    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
