- name: Create linux user if not exists
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Recursively delete /app directory if exists
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download {{component}} application"
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp/catalogue.zip

- name: Unarchive the {{component}} application
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes