- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Node.js 18
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install the dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
