- name: Add NodeSource Node.js 18 repo
  ansible.builtin.shell: |
    curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
  args:
    warn: false

- name: Install Node.js 18
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install the dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
