- name: Disable Old nodejs if exists
  ansible.builtin.shell: |
    dnf module disable nodejs -y
    ignore_errors: yes

- name: Enable nodejs:18 module if available
  ansible.builtin.shell: |
    dnf module enable nodejs:18 -y
    ignore_errors: yes

- name: Install Node.js 18 if missing
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install the dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
